///////////////////////////////////////////////////////////
//  Bouteille.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      06-févr.-2025 10:54:11
//  Original author: JMatz
///////////////////////////////////////////////////////////




public class Bouteille {

	private float contenuEnL;
	private float contenanceEnL ;
	private bool estOuverte;



	~Bouteille(){

	}

	public virtual void Dispose(){

	}

	public Bouteille(){

	}

	/// 
	/// <param name="_nom"></param>
	/// <param name="_contenuEnL"></param>
	/// <param name="_contenanceEnL"></param>
	/// <param name="ouverte"></param>
	public Bouteille(string _nom, float _contenuEnL, float _contenanceEnL, bool ouverte){

	}

	public bool Ouvrir(){

		return false;
	}

	public bool Fermer(){

		return false;
	}

	public bool Vider(){

		return false;
	}

	/// 
	/// <param name="quantiteEnLitre"></param>
	public float Vider(float quantiteEnLitre){

		return 0;
	}

	public bool Remplir(){

		return false;
	}

	/// 
	/// <param name="quantiteEnL"></param>
	public bool Remplir(float quantiteEnL){

		return false;
	}

}//end Bouteille